# Import the Libraries

In [33]:
import pandas as pd
import numpy as np
import glob
import re
import os

# Import Folder Path

In [34]:
folder_path = r"C:\Users\lenovo\Downloads\Survey of india Files Data"

# Import Csv Files

# Fetch June Data

In [35]:
import pandas as pd

# Read file
df = pd.read_csv(
    r"C:\Users\lenovo\Downloads\Survey of india Files Data\Region 1\region-1-1-2026-May-Jun.csv"
)

# Convert Date to datetime
df["Date"] = pd.to_datetime(
    df["Date"],
    format="%d-%m-%Y",
    errors="coerce"
)


# ---------------------------------------
# Start Date and End Date
# ---------------------------------------

start_date = "01-06-2026"
end_date = "30-06-2026"


# Convert start and end dates
start_date = pd.to_datetime(
    start_date,
    format="%d-%m-%Y"
)

end_date = pd.to_datetime(
    end_date,
    format="%d-%m-%Y"
)


# ---------------------------------------
# Filter data between Start and End Date
# ---------------------------------------

filtered_df = df[
    (df["Date"] >= start_date) &
    (df["Date"] <= end_date)
].copy()


# Check result
print("Start Date:", start_date.strftime("%d-%m-%Y"))
print("End Date:", end_date.strftime("%d-%m-%Y"))

print("Total records:", len(filtered_df))

print(filtered_df.head())

Start Date: 01-06-2026
End Date: 30-06-2026
Total records: 381552
        Date                                           FilePath  \
0 2026-06-01  D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...
1 2026-06-01  D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...
2 2026-06-01  D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...
3 2026-06-01  D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...
4 2026-06-01  D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...

        FileName  FileSize
0  ABOH152aB.zip      2393
1  ABOH152bB.zip      2393
2  ABOH152cB.zip      2484
3  ABOH152dB.zip      2540
4  ABOH152eB.zip      2628

# Drop Date Column

In [36]:
df = df.drop(columns ="Date")

# Fetch Column in the Path

In [37]:
import re

def extract_date(filepath):

    # Pattern 1:
    # Example: \2025\03\01\
    match1 = re.search(
        r"\\(\d{4})\\(\d{2})\\(\d{2})",
        filepath
    )

    if match1:
        return f"{match1.group(3)}-{match1.group(2)}-{match1.group(1)}"


    # Pattern 2:
    # Example: RefData.26\Month.Jun\Day.01
    match2 = re.search(
        r"RefData\.(\d{2})\\Month\.(\w{3})\\Day\.(\d{2})",
        filepath
    )

    if match2:

        year = f"20{match2.group(1)}"

        month_str = match2.group(2)

        day = match2.group(3)

        month_map = {
            "Jan": "01",
            "Feb": "02",
            "Mar": "03",
            "Apr": "04",
            "May": "05",
            "Jun": "06",
            "Jul": "07",
            "Aug": "08",
            "Sep": "09",
            "Oct": "10",
            "Nov": "11",
            "Dec": "12"
        }

        month = month_map.get(month_str, "00")

        return f"{day}-{month}-{year}"


    return None


# Create Date column
df["Date"] = df["FilePath"].apply(extract_date)


# Move Date column to first position
date_column = df.pop("Date")

df.insert(0, "Date", date_column)

In [38]:
# Convert Date to datetime
df["Date"] = pd.to_datetime(
    df["Date"],
    errors="coerce"
)

# ---------------------------------------
# Start Date and End Date
# ---------------------------------------

start_date = pd.to_datetime("01-06-2026")
end_date = pd.to_datetime("30-06-2026")


# ---------------------------------------
# Filter data
# ---------------------------------------

df_filtered = df[
    (df["Date"] >= start_date) &
    (df["Date"] <= end_date)
].copy()

# print("Start Date:", start_date.strftime("%d-%m-%Y"))
# print("End Date:", end_date.strftime("%d-%m-%Y"))
# print("Total files:", len(df_filtered))
df_filtered

C:\Users\lenovo\AppData\Local\Temp\ipykernel_21280\1587576140.py:12: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  end_date = pd.to_datetime("30-06-2026")

,Date,FilePath,FileName,FileSize
0,2026-01-06,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ABOH152aB.zip,2393
1,2026-01-06,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ABOH152bB.zip,2393
2,2026-01-06,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ABOH152cB.zip,2484
3,2026-01-06,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ABOH152dB.zip,2540
4,2026-01-06,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ABOH152eB.zip,2628
...,...,...,...,...
459363,2026-06-05,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ZIRO126tB.zip,2534
459364,2026-06-05,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ZIRO126uB.zip,2545
459365,2026-06-05,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ZIRO126vB.zip,2852
459366,2026-06-05,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ZIRO126wB.zip,3025
459367,2026-06-05,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ZIRO126xB.zip,2844

In [39]:
df = filtered_df

# Add New Column Fetch The Station Code

In [40]:
df["Station"] = df["FileName"].apply(lambda x: os.path.basename(x[:4]))
df

,Date,FilePath,FileName,FileSize,Station
0,2026-06-01,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ABOH152aB.zip,2393,ABOH
1,2026-06-01,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ABOH152bB.zip,2393,ABOH
2,2026-06-01,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ABOH152cB.zip,2484,ABOH
3,2026-06-01,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ABOH152dB.zip,2540,ABOH
4,2026-06-01,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ABOH152eB.zip,2628,ABOH
...,...,...,...,...,...
381547,2026-06-30,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ZIRO181tB.zip,3011,ZIRO
381548,2026-06-30,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ZIRO181uB.zip,2748,ZIRO
381549,2026-06-30,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ZIRO181vB.zip,2697,ZIRO
381550,2026-06-30,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ZIRO181wB.zip,2692,ZIRO
381551,2026-06-30,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ZIRO181xB.zip,2703,ZIRO

# Extension

In [41]:
df["Extension"] = df["FileName"].apply(lambda x: os.path.basename(x[-3:]))

In [42]:
df[df['Extension'] == "zip"]

,Date,FilePath,FileName,FileSize,Station,Extension
0,2026-06-01,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ABOH152aB.zip,2393,ABOH,zip
1,2026-06-01,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ABOH152bB.zip,2393,ABOH,zip
2,2026-06-01,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ABOH152cB.zip,2484,ABOH,zip
3,2026-06-01,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ABOH152dB.zip,2540,ABOH,zip
4,2026-06-01,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ABOH152eB.zip,2628,ABOH,zip
...,...,...,...,...,...,...
381547,2026-06-30,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ZIRO181tB.zip,3011,ZIRO,zip
381548,2026-06-30,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ZIRO181uB.zip,2748,ZIRO,zip
381549,2026-06-30,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ZIRO181vB.zip,2697,ZIRO,zip
381550,2026-06-30,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ZIRO181wB.zip,2692,ZIRO,zip
381551,2026-06-30,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,ZIRO181xB.zip,2703,ZIRO,zip

# State Filter

In [43]:
station_df = pd.read_excel(r"C:\Users\lenovo\Downloads\Region 2 Stations.xlsx")
station_df

          StationName              State StationCode StationCodeRenamed
0           DHARMAPUR  ANDAMAN & NICOBAR        DHPR               DHPR
1          MAYABUNDAR  ANDAMAN & NICOBAR        MAYA               MAYA
2          PHOENIXBAY  ANDAMAN & NICOBAR        PBAY               PBAY
3           SITANAGAR  ANDAMAN & NICOBAR        SITA               SITA
4         SOUTH CREEK  ANDAMAN & NICOBAR        SEEK               SEEK
...               ...                ...         ...                ...
1039        BISHNUPUR           W.Bengal        BISH               BISH
1040         DURGAPUR           W.Bengal        DURG               DURG
1041  YERRAGONDAPALEM     ANDHRA PRADESH        YGPM               YGPM
1042         YETAPAKA     ANDHRA PRADESH        YPKA               YPKA
1043           BOINDA             ODISHA        BOND               BOND

[1044 rows x 4 columns]

# Mark Specific State

In [ ]:
specific_state = station_df[
    (station_df["State"] == "MADH")  
]
specific_state

      StationName           State StationCode StationCodeRenamed
442      AJAUGARH  MADHYA PRADESH        AJAU               AJAU
443     ALIRAJPUR  MADHYA PRADESH        ALIR               ALIR
444      AMANGANJ  MADHYA PRADESH        AMAN               AMAN
445       ANUPPUR  MADHYA PRADESH        ANPR               ANPR
446          ARON  MADHYA PRADESH        ARON               ARON
..            ...             ...         ...                ...
527       TEOTHAR  MADHYA PRADESH        TEOT               TEOT
528  UJJAIN NAGAR  MADHYA PRADESH        UJJA               UJJA
529       UNCHERA  MADHYA PRADESH        UNCH               UNCH
530       VIDISHA  MADHYA PRADESH        VIDI               VIDI
531       BADUADA  MADHYA PRADESH        BADU               BADU

[90 rows x 4 columns]

# Check the state Both File have or not

In [45]:
df = df[df["Station"].isin(specific_state["StationCodeRenamed"])]

In [46]:
df.to_excel(r'C:\Users\lenovo\Desktop\June_Files\Madhya_Pradesh\State_Filter_File.xlsx')

# State Comparison

In [47]:
all_match = set(specific_state['StationCodeRenamed']) == set(df['Station'])

if all_match:
    print("All StationCode values match the Station values in df.")
else:
    #find the differences
    missing_in_df = set(specific_state['StationCodeRenamed']) - set(df['Station'])
    missing_in_station_codes_df = set(df['Station']) - set(specific_state['StationCodeRenamed'])
    
    print("Discrepancies found:")
    if  missing_in_df:
        print("Station codes in filtered_station but not in df:", missing_in_df)
    if missing_in_station_codes_df:
        print("Stations in combined_df but not in filtered_stations:", missing_in_station_codes_df)

Discrepancies found:
Station codes in filtered_station but not in df: {'AJAU'}

# Checking Invalid Files

In [48]:
import re

pattern2 = r'^[A-Za-z_]{4}\d{3}[A-Za-z]{2}\.zip$'
pattern3 = r'^[A-Za-z_]{3}\d{1}\d{3}[A-Za-z]{2}\.zip$'
pattern4 = r'^[A-Za-z_]{4}\d{3}[A-Za-z]\.T02$'
pattern5 = r'^[A-Za-z_]{3}\d{1}\d{3}[A-Za-z]\.T02$'

# New pattern
pattern6 = r'^[A-Za-z_]{4}\d{3}[A-Za-z]\d{2}[A-Za-z]\.zip$'


# Check FileName against all patterns
non_matching_files = df[
    ~(
        df["FileName"].str.match(pattern2, na=False)
        |
        df["FileName"].str.match(pattern3, na=False)
        |
        df["FileName"].str.match(pattern4, na=False)
        |
        df["FileName"].str.match(pattern5, na=False)
        |
        df["FileName"].str.match(pattern6, na=False)
    )
]


print("Files with non-matching patterns:")
print(non_matching_files[["FileName"]])

print("\nTotal non-matching files:", len(non_matching_files))

Files with non-matching patterns:
Empty DataFrame
Columns: [FileName]
Index: []

Total non-matching files: 0

# Valid Files

In [49]:
patterns = [pattern2,pattern3,pattern4,pattern5,pattern6]
valid_files = df[df["FileName"].apply(lambda x: any(re.match(pattern , x) for pattern in patterns))]

# Low  File Size(below 2000KB)

In [50]:
lower_file_size = df[df['FileSize'] <= 2000]
lower_file_size.to_excel(r"Lower File Size.xlsx")
lower_file_size

,Date,FilePath,FileName,FileSize,Station,Extension
3021,2026-06-01,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,DALO152aB.zip,229,DALO,zip
3022,2026-06-01,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,DALO152bB.zip,229,DALO,zip
3023,2026-06-01,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,DALO152cB.zip,231,DALO,zip
3024,2026-06-01,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,DALO152dB.zip,241,DALO,zip
3025,2026-06-01,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,DALO152eB.zip,251,DALO,zip
...,...,...,...,...,...,...
380040,2026-06-30,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,SEON181tB.zip,408,SEON,zip
380588,2026-06-30,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,SRNG181dB.zip,102,SRNG,zip
380589,2026-06-30,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,SRNG181eB.zip,42,SRNG,zip
380590,2026-06-30,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,SRNG181fB.zip,1160,SRNG,zip
380591,2026-06-30,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,SRNG181gB.zip,1953,SRNG,zip

# Dupliactes Files

In [51]:
# Convert Date to datetime
df["Date"] = pd.to_datetime(
    df["Date"],
    errors="coerce"
)

# Start Date
start_date = pd.to_datetime("06-01-2026")

# End Date
end_date = pd.to_datetime("30-06-2026")

# Filter data by date
df_filtered = df[
    (df["Date"] >= start_date) &
    (df["Date"] <= end_date)
].copy()

print("Start Date:", start_date.strftime("%d-%m-%Y"))
print("End Date:", end_date.strftime("%d-%m-%Y"))
print("Total files:", len(df_filtered))

Start Date: 01-06-2026
End Date: 30-06-2026
Total files: 63005

C:\Users\lenovo\AppData\Local\Temp\ipykernel_21280\286937110.py:11: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  end_date = pd.to_datetime("30-06-2026")

# Hourly File Data

In [52]:
import re
import os

# Pattern given by mentor
invalid_pattern = re.compile(r"^[A-Z]{4}\d{3}\[a]\..+$")

# Find files that do NOT match the pattern
invalid_files = df_filtered[
    df_filtered["FileName"].astype(str).str.match(
        invalid_pattern
    )
].copy()

# Take only required columns
invalid_file_list = invalid_files[
    ["Date", "FileName", "Station"]
].copy()

# Output folder
output_folder = r"C:\Users\lenovo\Desktop\June_Files\Madhya_Pradesh\Hourly_File_Date.xlsx"

# Make sure folder exists
os.makedirs(output_folder, exist_ok=True)

# Output Excel file
output_file = os.path.join(
    output_folder,
    "June_2026_Invalid_Files.xlsx"
)

# Save
invalid_file_list.to_excel(
    output_file,
    index=False
)

# Display result
print("Invalid Files:")
print(invalid_file_list)

print("\nTotal Invalid Files:", len(invalid_file_list))

print("\nFile saved successfully:")
print(output_file)

Invalid Files:
Empty DataFrame
Columns: [Date, FileName, Station]
Index: []

Total Invalid Files: 0

File saved successfully:
C:\Users\lenovo\Desktop\June_Files\Madhya_Pradesh\Hourly_File_Date.xlsx\June_2026_Invalid_Files.xlsx

# Wrong Julain Code

In [53]:
df["Date_Julian"] = df["Date"].dt.strftime("%j")

df["Path_Julian"] = df["FilePath"].str.extract(
    r'[A-Za-z]{3,4}(\d{3})'
)

df["Julian_Match"] = (
    df["Date_Julian"] == df["Path_Julian"]
)

print(
    df[
        ["Date", "FileName", "Date_Julian", "Path_Julian", "Julian_Match"]
    ]
)

             Date       FileName Date_Julian Path_Julian  Julian_Match
129    2026-06-01  ALIR152aB.zip         152         152          True
130    2026-06-01  ALIR152bB.zip         152         152          True
131    2026-06-01  ALIR152cB.zip         152         152          True
132    2026-06-01  ALIR152dB.zip         152         152          True
133    2026-06-01  ALIR152eB.zip         152         152          True
...           ...            ...         ...         ...           ...
381259 2026-06-30  VIDI181tB.zip         181         181          True
381260 2026-06-30  VIDI181uB.zip         181         181          True
381261 2026-06-30  VIDI181vB.zip         181         181          True
381262 2026-06-30  VIDI181wB.zip         181         181          True
381263 2026-06-30  VIDI181xB.zip         181         181          True

[63005 rows x 5 columns]

In [54]:
df[df['Julian_Match'] == False]

,Date,FilePath,FileName,FileSize,Station,Extension,Date_Julian,Path_Julian,Julian_Match
11236,2026-06-01,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,SAT3152aB.zip,3263,SAT3,zip,152,315,False
11237,2026-06-01,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,SAT3152bB.zip,3196,SAT3,zip,152,315,False
11238,2026-06-01,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,SAT3152cB.zip,3294,SAT3,zip,152,315,False
11239,2026-06-01,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,SAT3152dB.zip,3458,SAT3,zip,152,315,False
11240,2026-06-01,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,SAT3152eB.zip,3641,SAT3,zip,152,315,False
...,...,...,...,...,...,...,...,...,...
379980,2026-06-30,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,SAT3181tB.zip,3607,SAT3,zip,181,318,False
379981,2026-06-30,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,SAT3181uB.zip,3579,SAT3,zip,181,318,False
379982,2026-06-30,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,SAT3181vB.zip,3425,SAT3,zip,181,318,False
379983,2026-06-30,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,SAT3181wB.zip,3156,SAT3,zip,181,318,False
379984,2026-06-30,D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...,SAT3181xB.zip,3176,SAT3,zip,181,318,False

# Fetch the Daily File Distribution

In [55]:
import pandas as pd

# Convert Date column to datetime
df_filtered["Date"] = pd.to_datetime(
    df_filtered["Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

# Create Day column
df_filtered["Day"] = df_filtered["Date"].dt.strftime("%d-%m-%Y")

# Daily-wise distribution
Daily_result = df_filtered.pivot_table(
    index="Date",
    columns="Station",
    aggfunc="size",
    fill_value=0
)

Daily_result = Daily_result.sort_index()

print(Daily_result)

Station     ALIR  AMAN  ANPR  ARON  ASHT  BABA  BADA  BADO  BADU  BAIH  ...  \
Date                                                                    ...
2026-06-01    24    24    24    24    24    24    24    24    24    24  ...
2026-06-02    24    24    24    24    24    24    24    24    24    24  ...
2026-06-03    24    24    24    24    24    24    24    24    24    24  ...
2026-06-04    24    24    24    24    24    24    24    24    24    24  ...
2026-06-05    24    24    24    24    24    24    24    24    24    24  ...
2026-06-06    24    24    24    24    24    24    24    23    24    24  ...
2026-06-07    24    24    24    24    24    24    24    21    24    24  ...
2026-06-08    24    24    24    24    24    24    24    21    24    24  ...
2026-06-09    24    24    24    24    24    24    24    22     4    24  ...
2026-06-10    24    24    24    24    24    24    24    20    16    24  ...
2026-06-11    24    24    24    24    24    24    24    21     2    24  ...
2026-06-12    24    24    24    24    24    24    24    20     5    24  ...
2026-06-13    24    24    24    24    24    24    24    20    15    24  ...
2026-06-14    24    24    24    24    24    24    24    20    13    24  ...
2026-06-15    24    24    24    24    24    24    24    20     2    24  ...
2026-06-16    24    24    24    24    24    24    24    21     2    24  ...
2026-06-17    24    24    24    24    24    24    24    17     4    24  ...
2026-06-18    24    24    24    24    24    24    24    18     5    24  ...
2026-06-19    24    24    24    24    24    24    24    13     7    24  ...
2026-06-20    24    24    24    24    24    24    24     0     3    24  ...
2026-06-21    24    24    24    24    24    24    24     0     3    24  ...
2026-06-22    24    24    24    24    24    24    24     0     2    24  ...
2026-06-23    24    24    24    24    24    24    24     0     1    24  ...
2026-06-24    24    24    24    24    24    24    24     0     1    24  ...
2026-06-25    24    24    24    24    24    24    24     0     2    24  ...
2026-06-26    24    24    24    24    24    24    24     0    22    24  ...
2026-06-27    24    24    24    24    24    24    24     0    24    24  ...
2026-06-28    24    24    24    24    24    24    24     0    24    24  ...
2026-06-29    24    24    24    24    24    24    24     0    24    24  ...
2026-06-30    24    24    24    24    24    24    24     0    24    24  ...

Station     SILW  SING  SIRA  SRNG  SRNJ  STMP  TEOT  UJJA  UNCH  VIDI
Date
2026-06-01    24    24    24    24    24    24    24    24    24    24
2026-06-02    24    24    24    24    24    24    24    24    24    24
2026-06-03    24    24    24    24    24    24    24    24    24    24
2026-06-04    24    24    24    24    24    24    24    24    24    24
2026-06-05    24    24    24    24    24    24    24    24    24    24
2026-06-06    24    24    24    24    24    24    24    24    24    24
2026-06-07    24    24    24    24    24    24    24    24    24    24
2026-06-08    24    24    24    24    24    24    24    24    24    24
2026-06-09    24    24    24    24    24    24    24    24    24    24
2026-06-10    24    24    24    24    24    24    24    24    24    24
2026-06-11    24    24    24    24    24    24    24    24    24    24
2026-06-12    24    24    24    24    24    24    24    24    24    24
2026-06-13    24    24    24    24    24    24    24    24    24    24
2026-06-14    24    24    24    20    24    24    24    24    24    24
2026-06-15    24    24    24     9    24    24    24    24    24    24
2026-06-16    24    24    24     3    24    24    24    24    24    24
2026-06-17    24    24    24     3    24    24    24    24    24    24
2026-06-18    24    24    24     5    24    24    24    24    24    24
2026-06-19    24    24    24     3    24    24    24    24    24    24
2026-06-20    24    24    24     4    24    24    24    24    24    24
2026-06-21    24    24    24     4    24    24    24    24    24    24
2026-06-22    24    24    24     5    24    24    24    24    24    24
2026-06-23    24    24    24     2    24    24    24    24    24    24
2026-06-24    24    24    24     5    24    24    24    24    24    24
2026-06-25    24    24    24     4    24    24    24    24    24    24
2026-06-26    24    24    24     6    24    24    24    24    24    24
2026-06-27    24    24    24     5    24    24    24    24    24    24
2026-06-28    24    24    24     5    24    24    24    24    24    24
2026-06-29    24    24    24     2    24    24    24    24    24    24
2026-06-30    24    24    24     4    24    24    24    24    24    24

[30 rows x 89 columns]

In [64]:
# Save Daily Distribution to Excel

output_file = r"C:\Users\lenovo\Desktop\June_Files\Madhya_Pradesh\Daily_Distribution.xlsx"

Daily_result.to_excel(
    output_file,
    index=True,
    sheet_name="Daily Distribution"
)

print("\nDaily distribution saved successfully:")
print(output_file)

Daily distribution saved successfully:
C:\Users\lenovo\Desktop\June_Files\Madhya_Pradesh\Daily_Distribution.xlsx

# Daily Wise Distribution in Valid Files

In [57]:
import pandas as pd

# Convert Date column to datetime
valid_files["Date"] = pd.to_datetime(
    valid_files["Date"],
    format="%d-%m-%Y",
    errors="coerce"
)

# Create Day column
valid_files["Day"] = valid_files["Date"].dt.strftime("%d-%m-%Y")

# Daily-wise distribution of VALID files
Daily_result_Valid_Files = valid_files.pivot_table(
    index="Date",
    columns="Station",
    aggfunc="size",
    fill_value=0
)

Daily_result_Valid_Files = Daily_result_Valid_Files.sort_index()

print(Daily_result_Valid_Files)

Station     ALIR  AMAN  ANPR  ARON  ASHT  BABA  BADA  BADO  BADU  BAIH  ...  \
Date                                                                    ...
2026-06-01    24    24    24    24    24    24    24    24    24    24  ...
2026-06-02    24    24    24    24    24    24    24    24    24    24  ...
2026-06-03    24    24    24    24    24    24    24    24    24    24  ...
2026-06-04    24    24    24    24    24    24    24    24    24    24  ...
2026-06-05    24    24    24    24    24    24    24    24    24    24  ...
2026-06-06    24    24    24    24    24    24    24    23    24    24  ...
2026-06-07    24    24    24    24    24    24    24    21    24    24  ...
2026-06-08    24    24    24    24    24    24    24    21    24    24  ...
2026-06-09    24    24    24    24    24    24    24    22     4    24  ...
2026-06-10    24    24    24    24    24    24    24    20    16    24  ...
2026-06-11    24    24    24    24    24    24    24    21     2    24  ...
2026-06-12    24    24    24    24    24    24    24    20     5    24  ...
2026-06-13    24    24    24    24    24    24    24    20    15    24  ...
2026-06-14    24    24    24    24    24    24    24    20    13    24  ...
2026-06-15    24    24    24    24    24    24    24    20     2    24  ...
2026-06-16    24    24    24    24    24    24    24    21     2    24  ...
2026-06-17    24    24    24    24    24    24    24    17     4    24  ...
2026-06-18    24    24    24    24    24    24    24    18     5    24  ...
2026-06-19    24    24    24    24    24    24    24    13     7    24  ...
2026-06-20    24    24    24    24    24    24    24     0     3    24  ...
2026-06-21    24    24    24    24    24    24    24     0     3    24  ...
2026-06-22    24    24    24    24    24    24    24     0     2    24  ...
2026-06-23    24    24    24    24    24    24    24     0     1    24  ...
2026-06-24    24    24    24    24    24    24    24     0     1    24  ...
2026-06-25    24    24    24    24    24    24    24     0     2    24  ...
2026-06-26    24    24    24    24    24    24    24     0    22    24  ...
2026-06-27    24    24    24    24    24    24    24     0    24    24  ...
2026-06-28    24    24    24    24    24    24    24     0    24    24  ...
2026-06-29    24    24    24    24    24    24    24     0    24    24  ...
2026-06-30    24    24    24    24    24    24    24     0    24    24  ...

Station     SILW  SING  SIRA  SRNG  SRNJ  STMP  TEOT  UJJA  UNCH  VIDI
Date
2026-06-01    24    24    24    24    24    24    24    24    24    24
2026-06-02    24    24    24    24    24    24    24    24    24    24
2026-06-03    24    24    24    24    24    24    24    24    24    24
2026-06-04    24    24    24    24    24    24    24    24    24    24
2026-06-05    24    24    24    24    24    24    24    24    24    24
2026-06-06    24    24    24    24    24    24    24    24    24    24
2026-06-07    24    24    24    24    24    24    24    24    24    24
2026-06-08    24    24    24    24    24    24    24    24    24    24
2026-06-09    24    24    24    24    24    24    24    24    24    24
2026-06-10    24    24    24    24    24    24    24    24    24    24
2026-06-11    24    24    24    24    24    24    24    24    24    24
2026-06-12    24    24    24    24    24    24    24    24    24    24
2026-06-13    24    24    24    24    24    24    24    24    24    24
2026-06-14    24    24    24    20    24    24    24    24    24    24
2026-06-15    24    24    24     9    24    24    24    24    24    24
2026-06-16    24    24    24     3    24    24    24    24    24    24
2026-06-17    24    24    24     3    24    24    24    24    24    24
2026-06-18    24    24    24     5    24    24    24    24    24    24
2026-06-19    24    24    24     3    24    24    24    24    24    24
2026-06-20    24    24    24     4    24    24    24    24    24    24
2026-06-21    24    24    24     4    24    24    24    24    24    24
2026-06-22    24    24    24     5    24    24    24    24    24    24
2026-06-23    24    24    24     2    24    24    24    24    24    24
2026-06-24    24    24    24     5    24    24    24    24    24    24
2026-06-25    24    24    24     4    24    24    24    24    24    24
2026-06-26    24    24    24     6    24    24    24    24    24    24
2026-06-27    24    24    24     5    24    24    24    24    24    24
2026-06-28    24    24    24     5    24    24    24    24    24    24
2026-06-29    24    24    24     2    24    24    24    24    24    24
2026-06-30    24    24    24     4    24    24    24    24    24    24

[30 rows x 89 columns]

# Missing File

In [58]:
import pandas as pd
import re


# =========================================================
# 1. VALID FILE PATTERNS
# =========================================================

patterns = [
    pattern2,
    pattern3,
    pattern4,
    pattern5,
    pattern6
]


# =========================================================
# 2. TAKE ONLY JUNE DATA
# =========================================================

# IMPORTANT:
# Use df_filtered, NOT df
# because df_filtered contains only June 2026

valid_files = df_filtered[
    df_filtered["FileName"].apply(
        lambda x: any(
            re.match(pattern, str(x))
            for pattern in patterns
        )
    )
].copy()


# =========================================================
# 3. MAKE SURE DATE IS DATETIME
# =========================================================

valid_files["Date"] = pd.to_datetime(
    valid_files["Date"],
    errors="coerce"
)


# =========================================================
# 4. FIND NUMBER OF DAYS
# =========================================================

start_date = valid_files["Date"].min()
end_date = valid_files["Date"].max()

number_of_days = (
    end_date - start_date
).days + 1


# =========================================================
# 5. FIND NUMBER OF STATIONS
# =========================================================

stations = sorted(
    df_filtered["Station"]
    .dropna()
    .unique()
)

number_of_stations = len(stations)


# =========================================================
# 6. EXPECTED FILES PER DAY
# =========================================================

files_per_station_per_day = 24


# =========================================================
# 7. CALCULATE EXPECTED TOTAL AUTOMATICALLY
# =========================================================

expected_files = (
    number_of_days
    * number_of_stations
    * files_per_station_per_day
)


print("========================================")
print("EXPECTED FILE CALCULATION")
print("========================================")

print("Start Date              :", start_date.strftime("%d-%m-%Y"))
print("End Date                :", end_date.strftime("%d-%m-%Y"))
print("Number of Days          :", number_of_days)
print("Number of Stations      :", number_of_stations)
print("Files per Station/Day   :", files_per_station_per_day)

print(
    "\nExpected Files =",
    number_of_days,
    "*",
    number_of_stations,
    "*",
    files_per_station_per_day
)

print("Expected Total Files    :", expected_files)


# =========================================================
# 8. ACTUAL VALID FILES
# =========================================================

actual_valid_files = len(valid_files)

print("\nActual Valid Files      :", actual_valid_files)


# =========================================================
# 9. TOTAL MISSING FILES
# =========================================================

total_missing_files = (
    expected_files - actual_valid_files
)

print("Total Missing Files     :", total_missing_files)


# =========================================================
# 10. COUNT VALID FILES
#     DATE + STATION
# =========================================================

valid_count = valid_files.pivot_table(
    index="Date",
    columns="Station",
    aggfunc="size",
    fill_value=0
)


# =========================================================
# 11. CREATE ALL JUNE DATES
# =========================================================

expected_dates = pd.date_range(
    start=start_date,
    end=end_date,
    freq="D"
)


# =========================================================
# 12. MAKE COMPLETE DATE × STATION TABLE
# =========================================================

valid_count = valid_count.reindex(
    index=expected_dates,
    columns=stations,
    fill_value=0
)


# =========================================================
# 13. CALCULATE MISSING FILES
# =========================================================

missing_pivot = (
    files_per_station_per_day
    - valid_count
)


# Prevent negative values
missing_pivot = missing_pivot.clip(
    lower=0
)


# =========================================================
# 14. DISPLAY MISSING FILE PIVOT
# =========================================================

print("\n========================================")
print("JUNE 2026 - MISSING FILE PIVOT")
print("========================================")

print(missing_pivot)


# =========================================================
# 15. TOTAL MISSING FROM PIVOT
# =========================================================

pivot_missing_total = int(
    missing_pivot.sum().sum()
)

print(
    "\nMissing Files from Pivot:",
    pivot_missing_total
)


# =========================================================
# 16. VERIFY BOTH CALCULATIONS
# =========================================================

print("\n========================================")
print("VERIFICATION")
print("========================================")

print(
    "Expected - Actual      :",
    total_missing_files
)

print(
    "Missing from Pivot     :",
    pivot_missing_total
)


if total_missing_files == pivot_missing_total:
    print("\n✓ Both missing-file counts MATCH.")
else:
    print("\n⚠ Counts DO NOT match.")
    print("Check your valid-file patterns or station data.")


# =========================================================
# 17. SAVE MISSING FILE PIVOT
# =========================================================

output_file = r"C:\Users\lenovo\Desktop\June_Files\Madhya_Pradesh\Missing_File.xlsx"

missing_pivot.to_excel(
    output_file
)

print("\nPivot table saved successfully:")
print(output_file)


# =========================================================
# SAVE MISSING FILE PIVOT TO EXCEL
# =========================================================

output_file = r"C:\Users\lenovo\Desktop\June_Files\Madhya_Pradesh.xlsx"

missing_pivot.to_excel(
    output_file,
    index=True,
    sheet_name="Missing Files"
)

print("\nMissing file pivot saved successfully:")
print(output_file)

========================================
EXPECTED FILE CALCULATION
========================================
Start Date              : 01-06-2026
End Date                : 30-06-2026
Number of Days          : 30
Number of Stations      : 89
Files per Station/Day   : 24

Expected Files = 30 * 89 * 24
Expected Total Files    : 64080

Actual Valid Files      : 63005
Total Missing Files     : 1075

========================================
JUNE 2026 - MISSING FILE PIVOT
========================================
Station     ALIR  AMAN  ANPR  ARON  ASHT  BABA  BADA  BADO  BADU  BAIH  ...  \
2026-06-01     0     0     0     0     0     0     0     0     0     0  ...
2026-06-02     0     0     0     0     0     0     0     0     0     0  ...
2026-06-03     0     0     0     0     0     0     0     0     0     0  ...
2026-06-04     0     0     0     0     0     0     0     0     0     0  ...
2026-06-05     0     0     0     0     0     0     0     0     0     0  ...
2026-06-06     0     0     0     0     0     0     0     1     0     0  ...
2026-06-07     0     0     0     0     0     0     0     3     0     0  ...
2026-06-08     0     0     0     0     0     0     0     3     0     0  ...
2026-06-09     0     0     0     0     0     0     0     2    20     0  ...
2026-06-10     0     0     0     0     0     0     0     4     8     0  ...
2026-06-11     0     0     0     0     0     0     0     3    22     0  ...
2026-06-12     0     0     0     0     0     0     0     4    19     0  ...
2026-06-13     0     0     0     0     0     0     0     4     9     0  ...
2026-06-14     0     0     0     0     0     0     0     4    11     0  ...
2026-06-15     0     0     0     0     0     0     0     4    22     0  ...
2026-06-16     0     0     0     0     0     0     0     3    22     0  ...
2026-06-17     0     0     0     0     0     0     0     7    20     0  ...
2026-06-18     0     0     0     0     0     0     0     6    19     0  ...
2026-06-19     0     0     0     0     0     0     0    11    17     0  ...
2026-06-20     0     0     0     0     0     0     0    24    21     0  ...
2026-06-21     0     0     0     0     0     0     0    24    21     0  ...
2026-06-22     0     0     0     0     0     0     0    24    22     0  ...
2026-06-23     0     0     0     0     0     0     0    24    23     0  ...
2026-06-24     0     0     0     0     0     0     0    24    23     0  ...
2026-06-25     0     0     0     0     0     0     0    24    22     0  ...
2026-06-26     0     0     0     0     0     0     0    24     2     0  ...
2026-06-27     0     0     0     0     0     0     0    24     0     0  ...
2026-06-28     0     0     0     0     0     0     0    24     0     0  ...
2026-06-29     0     0     0     0     0     0     0    24     0     0  ...
2026-06-30     0     0     0     0     0     0     0    24     0     0  ...

Station     SILW  SING  SIRA  SRNG  SRNJ  STMP  TEOT  UJJA  UNCH  VIDI
2026-06-01     0     0     0     0     0     0     0     0     0     0
2026-06-02     0     0     0     0     0     0     0     0     0     0
2026-06-03     0     0     0     0     0     0     0     0     0     0
2026-06-04     0     0     0     0     0     0     0     0     0     0
2026-06-05     0     0     0     0     0     0     0     0     0     0
2026-06-06     0     0     0     0     0     0     0     0     0     0
2026-06-07     0     0     0     0     0     0     0     0     0     0
2026-06-08     0     0     0     0     0     0     0     0     0     0
2026-06-09     0     0     0     0     0     0     0     0     0     0
2026-06-10     0     0     0     0     0     0     0     0     0     0
2026-06-11     0     0     0     0     0     0     0     0     0     0
2026-06-12     0     0     0     0     0     0     0     0     0     0
2026-06-13     0     0     0     0     0     0     0     0     0     0
2026-06-14     0     0     0     4     0     0     0     0     0     0
2026-06-15     0     0     0    15     0     0     0     0     0     0
2026-06-16     0     0     0    21     0     0     0     0     0     0
2026-06-17     0     0     0    21     0     0     0     0     0     0
2026-06-18     0     0     0    19     0     0     0     0     0     0
2026-06-19     0     0     0    21     0     0     0     0     0     0
2026-06-20     0     0     0    20     0     0     0     0     0     0
2026-06-21     0     0     0    20     0     0     0     0     0     0
2026-06-22     0     0     0    19     0     0     0     0     0     0
2026-06-23     0     0     0    22     0     0     0     0     0     0
2026-06-24     0     0     0    19     0     0     0     0     0     0
2026-06-25     0     0     0    20     0     0     0     0     0     0
2026-06-26     0     0     0    18     0     0     0     0     0     0
2026-06-27     0     0     0    19     0     0     0     0     0     0
2026-06-28     0     0     0    19     0     0     0     0     0     0
2026-06-29     0     0     0    22     0     0     0     0     0     0
2026-06-30     0     0     0    20     0     0     0     0     0     0

[30 rows x 89 columns]

Missing Files from Pivot: 1075

========================================
VERIFICATION
========================================
Expected - Actual      : 1075
Missing from Pivot     : 1075

✓ Both missing-file counts MATCH.

Pivot table saved successfully:
C:\Users\lenovo\Desktop\June_Files\Madhya_Pradesh\Missing_File.xlsx

Missing file pivot saved successfully:
C:\Users\lenovo\Desktop\June_Files\Madhya_Pradesh.xlsx

In [59]:
df.to_excel(r'C:\Users\lenovo\Desktop\June_Files\Madhya_Pradesh\Missing_File.xlsx')

# Missing Character

In [60]:
import pandas as pd
import os

# =========================================================
# Expected hourly characters: a to x = 24 hours
# =========================================================

expected_chars = list("abcdefghijklmnopqrstuvwx")

missing_records = []


# =========================================================
# Check each Date + Station
# =========================================================

for (date, station), group in valid_files.groupby(
    ["Date", "Station"]
):

    # All filenames for this Date + Station
    filenames = group["FileName"].astype(str).tolist()

    # Get the hourly characters already present
    actual_chars = set(
        filename[7].lower()
        for filename in filenames
        if len(filename) > 7
    )

    # Find missing hourly characters
    missing_chars = [
        char
        for char in expected_chars
        if char not in actual_chars
    ]

    # -----------------------------------------------------
    # Process every missing character
    # -----------------------------------------------------

    for missing_char in missing_chars:

        # Use an existing filename as the template
        template_file = filenames[0]

        # Replace the hourly character at position 8
        missing_file = (
            template_file[:7]
            + missing_char
            + template_file[8:]
        )

        # Find the path of the template file
        template_row = group[
            group["FileName"] == template_file
        ].iloc[0]

        template_path = str(
            template_row["FilePath"]
        )

        # Replace filename in the existing path
        expected_filepath = os.path.join(
            os.path.dirname(template_path),
            missing_file
        )

        # File does not exist, therefore size is 0
        file_size = 0

        # Store result
        missing_records.append({
            "Date": date,
            "Station": station,
            "Hourly_Missing_Character": missing_char,
            "Missing_File": missing_file,
            "Expected_FilePath": expected_filepath,
            "FileSize": file_size
        })


# =========================================================
# Create final DataFrame
# =========================================================

missing_character_df = pd.DataFrame(
    missing_records
)


# =========================================================
# Display result
# =========================================================

print(missing_character_df)

# =========================================================
# Save Missing Hourly Files to Excel
# =========================================================

output_file = r"C:\Users\lenovo\Desktop\June_Files\Madhya_Pradesh\Missing_Character_File.xlsx"

missing_character_df.to_excel(
    output_file,
    index=False,
    sheet_name="Missing Hourly Files"
)

print("\nMissing hourly file report saved successfully:")
print(output_file)

          Date Station Hourly_Missing_Character   Missing_File  \
0   2026-06-06    BADO                        x  BADO157xB.zip
1   2026-06-07    BADO                        v  BADO158vB.zip
2   2026-06-07    BADO                        w  BADO158wB.zip
3   2026-06-07    BADO                        x  BADO158xB.zip
4   2026-06-08    BADO                        v  BADO159vB.zip
..         ...     ...                      ...            ...
806 2026-06-30    SRNG                        t  SRNG181tB.zip
807 2026-06-30    SRNG                        u  SRNG181uB.zip
808 2026-06-30    SRNG                        v  SRNG181vB.zip
809 2026-06-30    SRNG                        w  SRNG181wB.zip
810 2026-06-30    SRNG                        x  SRNG181xB.zip

                                     Expected_FilePath  FileSize
0    D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...         0
1    D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...         0
2    D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...         0
3    D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...         0
4    D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...         0
..                                                 ...       ...
806  D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...         0
807  D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...         0
808  D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...         0
809  D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...         0
810  D:\SOI_FTP\Region_1_Hatanaka\Hourly\RefData.26...         0

[811 rows x 6 columns]

Missing hourly file report saved successfully:
C:\Users\lenovo\Desktop\June_Files\Madhya_Pradesh\Missing_Character_File.xlsx

# Bar Chart

In [61]:
import pandas as pd

# Make sure FileSize is numeric
df_filtered["FileSize"] = pd.to_numeric(
    df_filtered["FileSize"],
    errors="coerce"
)

# Define size ranges
bins = list(range(0, 12001, 1000))

# Create size ranges
df_filtered["Size_Range"] = pd.cut(
    df_filtered["FileSize"],
    bins=bins,
    right=True
)

# Count files in each size range
size_range_count = (
    df_filtered["Size_Range"]
    .value_counts()
    .sort_index()
    .reset_index()
)

# Rename columns
size_range_count.columns = [
    "Size_Range",
    "File_Count"
]

print("File count in each size range:")
print(size_range_count)

File count in each size range:
        Size_Range  File_Count
0        (0, 1000]         882
1     (1000, 2000]         909
2     (2000, 3000]       42126
3     (3000, 4000]       19081
4     (4000, 5000]           3
5     (5000, 6000]           0
6     (6000, 7000]           0
7     (7000, 8000]           0
8     (8000, 9000]           0
9    (9000, 10000]           0
10  (10000, 11000]           0
11  (11000, 12000]           0

In [62]:
import plotly.graph_objects as go
import plotly.express as px

# Convert Size_Range to string
size_range_count["Size_Range"] = size_range_count["Size_Range"].astype(str)

# Normalize File_Count between 0 and 1 for color mapping
normalized = (size_range_count["File_Count"] - size_range_count["File_Count"].min()) / \
             (size_range_count["File_Count"].max() - size_range_count["File_Count"].min())

# Generate Viridis colors based on normalized File_Count
viridis_colors = px.colors.sample_colorscale("Viridis", normalized)

fig = go.Figure()
fig.add_trace(go.Bar(
    x=size_range_count["Size_Range"],
    y=size_range_count["File_Count"],
    marker=dict(
        color=viridis_colors,       # Apply Viridis based on File_Count
        line=dict(color="black", width=1)
    ),
    text=[f"{int(count):,}" for count in size_range_count["File_Count"]],
    textposition='inside'
))

fig.update_layout(
    yaxis_type="log",
    xaxis_title="Size Range (KB)",
    yaxis_title="File Count (Log Scale)",
    title="File Count by Size Range (Filtered)",
    xaxis_tickangle=-45,
    width=1400,
    height=600,
    template="plotly_white"
)

fig

# Expected Output and Actual output File

In [63]:
#  Output File
station_file_count = (
    valid_files
    .groupby("Station")
    .size()
    .reset_index(name="Output_file")
)

# Expected Files

expected_per_station = (
    valid_files["Date"].nunique() * 24
    )

station_file_count["Expected File"] = expected_per_station

# Year

station_file_count["Year"] = (
    pd.to_datetime(valid_files["Date"])
    .dt.year
    .iloc[0]
)





# S.No
station_file_count.insert(
    0,
    "S.No",
    range(1, len(station_file_count) + 1)
)
# Arrange Columns

station_file_count = station_file_count[
    [
    "S.No",
    "Year",
    "Station",
    "Output_file",
    "Expected File"
]]

print(station_file_count)

# Save station-wise file summary to Excel

output_file = r"C:\Users\lenovo\Desktop\June_Files\Madhya_Pradesh\Summary_Of_Station.xlsx"

station_file_count.to_excel(
    output_file,
    index=False,
    sheet_name="Station Summary"
)

print("\nStation-wise file summary saved successfully:")
print(output_file)

    S.No  Year Station  Output_file  Expected File
0      1  2026    ALIR          720            720
1      2  2026    AMAN          720            720
2      3  2026    ANPR          720            720
3      4  2026    ARON          720            720
4      5  2026    ASHT          720            720
..   ...   ...     ...          ...            ...
84    85  2026    STMP          720            720
85    86  2026    TEOT          720            720
86    87  2026    UJJA          720            720
87    88  2026    UNCH          720            720
88    89  2026    VIDI          720            720

[89 rows x 5 columns]

Station-wise file summary saved successfully:
C:\Users\lenovo\Desktop\June_Files\Madhya_Pradesh\Summary_Of_Station.xlsx